= Veille technologique : préparation pour le CFP de Devoxx France 2023
Thomas SCHWENDER <https://github.com/ardemius[@ardemius]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:source-highlighter: highlightjs
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
:sectnums:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

toc::[]

== Overview

Proposition de sujet (conférence) pour Devoxx France 2023

Talk sur comment bien se préparer à un salon technologique : ce qu'il est bon d'en retirer, les pièges à éviter, etc.

*Thème principal* : People & Culture, Soft Skills, Future of work, Innovation, Side projects

*Niveau de la présentation* : Ouvert à tout niveau d'audience, débutant comme expert

*Tags* : 

    * methodology
    * discovery
    * experience
    * tools

== Recherche du nom de la conférence

* Devenez le maître de votre veille technologique
* Veille technologique, ne soyez pas son esclave
* Veille technologique : s'organiser pour la maîtriser (PAS MAL)
* Veille technologique : réussir à s'organiser pour apprendre en continu
* Pipeline de veille technologique : je veille donc je suis (et je suis BIEN 😌)
* *Pipeline de veille technologique : je veille donc je suis (et je suis zen 😌)*

Brainstorming : 

    * conjuguer travail et passion
    * Un titre parlant du pipeline de veille ? +
    Parler de "VeillOPS" -> non, c'est nul... 😓
    * *Pipeline de veille technologique : je veille donc je suis (et je suis bien 😌)* 
        ** -> AH YES ! TOP, on garde
        ** avec l'emoji "relieved face"
        ** ou celle du yoga ? 🧘

== Abstract

Talk ayant pour objectif d'expliquer comment réaliser une veille technologique efficace : 

    * qui soit soutenable, 
    * agréable à réaliser
    * et PAS éphémère (on prend des notes !)

Brainstorming : 

    * Parler du pipeline de veille
    * minimum de discipline mais maximum de plaisir ET d'utilité
    * amélioration continue

Draft : 

* Se tenir au courant des dernières évolutions technologiques est une nécessité dans nos métiers de la Tech. +

* Or, si dans notre monde connecté trouver de l'information n'est pas difficile, trouver la BONNE information, celle qui vous est réellement utile, l'est nettement plus. +
* Or, dans notre monde hyper connecté, trouver la BONNE information, sans se noyer, y passer sa vie et en gardant du plaisir à le faire, peut vite devenir un vrai casse-tête.

* De plus, c'est bien beau de trouver de l'information, mais encore faut-il rendre cette dernière utile et exploitable
* De plus, une fois trouvée, il serait bon de rendre cette information exploitable et non oubliée au bout de 2 semaines...

* NON : Les personnes à suivre et les types de media à notre disposition sont nombreux, certains sont mis à jour plusieurs fois par jour, tant et si bien qu'il est facile de se noyer dans le volume d'information et de finir par laisser tomber écoeuré.

* C'est tout l'intérêt de ce talk, vous expliquer comment, sans se faire mal, mettre en place un vrai petit "pipeline" de veille technologique vous permettant de réaliser une veille utile tout en conservant le plaisir d'avoir le nez dans la tech 😉
* C'est tout l'objectif de ce talk, vous expliquer comment, sans se faire mal, mettre en place un vrai petit "pipeline" de veille technologique vous permettant de réaliser une veille utile tout en conservant le plaisir d'avoir le nez dans la tech 😉

* Nous parlerons entre autres des moyens de sélectionner ses sujets de veille, comment les organiser et au final comment les transformer en une véritable base de connaissances qui vous suivra partout au quotidien.

* Dans cet article, je vais vous présenter mes astuces et mes ressources pour garder le contrôle sur l'information, afin de réussir votre veille technologique : 
	** XXX
	** et bien d'autres encore 😉

.version finale
----
Se tenir au courant des dernières évolutions technologiques est une nécessité dans nos métiers de la Tech.
Or, dans notre monde hyper connecté, trouver la BONNE information, sans se noyer, y passer sa vie et en gardant du plaisir à le faire, peut vite devenir un vrai casse-tête.
De plus, une fois trouvée, il serait bon de rendre cette information exploitable et non oubliée au bout de 2 semaines...

C'est tout l'objectif de ce talk, vous expliquer comment, sans se faire mal, mettre en place un vrai petit "pipeline" de veille technologique vous permettant de réaliser une veille utile tout en conservant le plaisir d'avoir le nez dans la tech 😉
Nous parlerons entre autres des moyens de sélectionner ses sujets de veille, comment les organiser et au final comment les transformer en une véritable base de connaissances qui vous suivra partout au quotidien.
----

.version finale - markdown
----
Se tenir au courant des dernières évolutions technologiques est une nécessité dans nos métiers de la Tech.  
Or, dans notre monde hyper connecté, trouver la **BONNE** information, **sans se noyer**, y passer sa vie et en gardant du **plaisir** à le faire, peut vite devenir un vrai casse-tête.  
De plus, une fois trouvée, il serait bon de **rendre cette information exploitable** et non oubliée au bout de 2 semaines...

C'est tout l'objectif de ce talk, vous expliquer comment, sans se faire mal, mettre en place un vrai petit **"pipeline" de veille technologique** vous permettant de réaliser une veille utile tout en conservant le plaisir d'avoir le nez dans la tech 😉  
Nous parlerons entre autres des moyens de **sélectionner** ses sujets de veille, comment les **organiser** et au final comment les transformer en une véritable **base de connaissances** qui vous suivra partout au quotidien.
----

== Message pour le comité

.version finale
----
Le sujet de la veille technologique et comment ne pas la "subir" mais bien au contraire la rendre "saine" et la plus utile possible me tient à coeur depuis longtemps.
J'en parle et fais des REX dessus depuis des années aux réunions de la communauté technique de Softeam, car j'ai pu constater que rares étaient les personnes réellement "sereines" dans l'exercice de leur veille : sans une bonne méthodologie, on se retrouve vite noyé dans le flux d'information et devant une masse de travail qui tue tout plaisir et nous fait jeter l'éponge.
J'ai décidé dernièrement de formaliser davantage mes conseils et retours d'expérience pour en faire un talk.

Celui-ci s'inscrit d'ailleurs dans la continuité de l'article que j'avais écrit en 2021 pour le blog de Devoxx France, "Comment bien préparer sa participation à Devoxx France" (https://www.devoxx.fr/2022/03/14/comment-bien-preparer-sa-participation-a-devoxx-france/), où j'avais déjà présenté la base de connaissances dans laquelle je persiste mes notes de conférences (https://github.com/Ardemius/meetups-talks-conferences-notes)

L'idée est ici de présenter la méthodologie que j'ai mise en place avec le temps pour organiser ma captation d'information.
Je suis aujourd'hui principalement placé en tant qu'architecte, maîtriser ma récupération de l'information et son exploitation sont mon quotidien.
J'en suis arrivé à la conclusion qu'il y avait une forte analogie entre la façon de gérer sa veille et les pipelines de traitement de la "data" : ingérer / traiter / analyser et persister deviennent sélectionner / consulter / exploiter et persister.

Cette méthodologie m'a permis d'arriver à certaine "plénitude" dans ma veille : je sais qu'elle est soutenable, super utile et je trouve du plaisir à la faire.

J'ai déjà pu en partie présenter le contenu de ce talk à ma communauté technique, et ai obtenu de très bons retours : on "démystifie" les choses, on montre qu'un résultat tangible peut être obtenu sans y sacrifier sa vie, et qu'on peut même y prendre du plaisir (ce qui est un retour qui fait vraiment du bien 🙂)
----

.markdown
----
Le sujet de la veille technologique et comment **ne pas la "subir"** mais bien au contraire la rendre **"saine"** et la plus **utile** possible me tient à coeur depuis longtemps.  
J'en parle et fais des REX dessus depuis des années aux réunions de la communauté technique de Softeam, car j'ai pu constater que rares étaient les personnes réellement "sereines" dans l'exercice de leur veille : sans une bonne méthodologie, on se retrouve vite noyé dans le flux d'information et devant une masse de travail qui tue tout plaisir et nous fait jeter l'éponge.  
J'ai décidé dernièrement de formaliser davantage mes conseils et retours d'expérience pour en faire un talk.

Celui-ci s'inscrit d'ailleurs dans la continuité de l'article que j'avais écrit en 2021 pour le blog de Devoxx France, "Comment bien préparer sa participation à Devoxx France" (https://www.devoxx.fr/2022/03/14/comment-bien-preparer-sa-participation-a-devoxx-france/), où j'avais déjà présenté la **base de connaissances** dans laquelle je persiste mes notes de conférences (https://github.com/Ardemius/meetups-talks-conferences-notes)

L'idée est ici de **présenter la méthodologie** que j'ai mise en place avec le temps pour organiser ma captation d'information.  
Je suis aujourd'hui principalement placé en tant qu'architecte, maîtriser ma récupération de l'information et son exploitation sont mon quotidien.  
J'en suis arrivé à la conclusion qu'il y avait une forte **analogie entre la façon de gérer sa veille et les pipelines de traitement de la "data"** : ingérer / traiter / analyser et persister deviennent sélectionner / consulter / exploiter et persister.

Cette méthodologie m'a permis d'arriver à certaine "plénitude" dans ma veille : je sais qu'elle est **soutenable**, super **utile** et je trouve du **plaisir** à la faire.

J'ai déjà pu en partie présenter le contenu de ce talk à ma communauté technique, et ai obtenu de très bons retours : on "démystifie" les choses, on montre qu'un résultat tangible peut être obtenu sans y sacrifier sa vie, et qu'on peut même y prendre du plaisir (ce qui est un retour qui fait vraiment du bien 🙂)
----




